server:
  port: 9010
  servlet:
    context-path: /auth

spring:
  application:
    name: data-hamal-auth
  profiles:
    active: dev
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        group: data-hamal
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/data_hamal?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      max-lifetime: 1800000
      idle-timeout: 60000
  # redis配置
  redis:
    # Redis数据库索引（默认为0）
    database: 8
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: 123456
    # 连接超时时间
    timeout: 10s
    connect-timeout: 30s
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0

sa-token:
  # token名称 (同时也是cookie名称)
  token-name: token
  # token有效期，单位s 默认7天, -1代表永不过期
  timeout: 604800
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: simple-uuid
  # 是否输出操作日志
  is-log: false

dubbo:
  application:
    name: ${spring.application.name}
    metadata-type: remote
    # 可选值 interface、instance、all，默认是 all，即接口级地址、应用级地址都注册
    register-mode: instance
  provider:
    token: true
  registry:
    address: nacos://${nacos.address:localhost}:8848?username=nacos&password=nacos
    group: data-hamal
  protocol:
    name: dubbo
    port: -1
