server:
  port: @data-hamal-auth.port@

spring:
  application:
    name: @project.artifactId@
  cloud:
    nacos:
      discovery:
        group: data-hamal
        server-addr: 127.0.0.1:8848
        namespace: 5e617ded-333c-4812-ad28-e9cd3b67512f
      config:
        group: ${spring.cloud.nacos.discovery.group}
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        namespace: ${spring.cloud.nacos.discovery.namespace}
  config:
    import:
      - optional:nacos:data-hamal-auth.yaml
      - optional:nacos:application-common.yaml
      - optional:nacos:application-db.yaml
      - optional:nacos:application-redis.yaml
      - optional:nacos:application-token.yaml
      - optional:nacos:application-dubbo.yaml
