server:
  port: 11020
  servlet:
    context-path: /hello

spring:
  application:
    name: data-hamal-service-hello


--- # nacos 配置
spring:
  cloud:
    nacos:
      # nacos 服务地址
      server-addr: 127.0.0.1:8848
      discovery:
        # 注册组
        group: data-hamal

dubbo:
  application:
    name: ${spring.application.name}
    metadata-type: remote
    # 可选值 interface、instance、all，默认是 all，即接口级地址、应用级地址都注册
    register-mode: instance
  provider:
    token: true
  registry:
    address: nacos://${nacos.address:localhost}:8848?username=nacos&password=nacos
    group: data-hamal
  protocol:
    name: dubbo
    port: -1
