version: '3.9'

services:
  # 基础服务
  mysql:
    image: mysql:8.0.30
    container_name: data-hamal-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    command: [
        'mysqld',
        '--innodb-buffer-pool-size=80M',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci',
        '--default-time-zone=+8:00',
        '--lower-case-table-names=1'
    ]
    volumes:
      - ./mysql.init:/docker-entrypoint-initdb.d
      - ./mysql.data:/var/lib/mysql
    networks:
      moss:
        ipv4_address: 10.13.145.10

  redis:
    image: redis:6.2.7
    container_name: data-hamal-redis
    restart: always
    ports:
      - "6379:6379"
      - "16379:16379"
    volumes:
      - ./redis.init/conf:/etc/redis
    networks:
      moss:
        ipv4_address: 10.13.145.20
    command: [ "redis-server", "/etc/redis/redis.conf", "--requirepass", "123456" ]

  zookeeper:
    image: zookeeper:3.8.0
    container_name: data-hamal-zookeeper
    restart: always
    ports:
      - "2181:2181"
    networks:
      moss:
        ipv4_address: 10.13.145.30

  nacos:
    image: striveonger/nacos:2.1.2
    container_name: data-hamal-nacos
    depends_on:
      - mysql # 只是控制了容器启动顺序, 但并不保证容器已经完全就绪
    healthcheck:
      test: [ "CMD-SHELL", "mysql --user=root --password=root --execute \"SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME='nacos'\" | grep 'nacos'" ]
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - "8848:8848"
      - "9848:9848"
    volumes:
      - ./nacos.init/conf:/usr/local/nacos/conf
    networks:
      moss:
        ipv4_address: 10.13.145.40

  # 应用服务
  gateway:
    build: ../data-hamal-gateway
    container_name: data-hamal-gateway
    ports:
      - "8080:8080"
    networks:
      moss:
        ipv4_address: 10.13.145.100
  auth:
    build: ../data-hamal-auth
    container_name: data-hamal-auth
    networks:
      moss:
        ipv4_address: 10.13.145.105
  provider-hello:
    build: ../data-hamal-providers/data-hamal-provider-hello
    container_name: data-hamal-provider-hello
    networks:
      moss:
        ipv4_address: 10.13.145.110
  provider-leaf:
    build: ../data-hamal-providers/data-hamal-provider-leaf
    container_name: data-hamal-provider-leaf
    networks:
      moss:
        ipv4_address: 10.13.145.115
  service-hello:
    build: ../data-hamal-services/data-hamal-service-hello
    container_name: data-hamal-service-hello
    networks:
      moss:
        ipv4_address: 10.13.145.120

networks:
  moss:
    driver: bridge
    ipam:
      config:
        - subnet: 10.13.145.0/24
          gateway: 10.13.145.9

