server:
  port: @data-hamal-provider-leaf.port@

spring:
  application:
    name: @project.artifactId@
  cloud:
    nacos:
      discovery:
        group: @nacos.group@
        server-addr: @nacos.server-addr@
        namespace: @nacos.namespace@
      config:
        group: ${spring.cloud.nacos.discovery.group}
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        namespace: ${spring.cloud.nacos.discovery.namespace}
  config:
    import:
      - optional:nacos:data-hamal-provider-leaf.yaml
      - optional:nacos:application-common.yaml
      - optional:nacos:application-db.yaml
      - optional:nacos:application-dubbo.yaml
