server:
  port: 9020
  servlet:
    context-path: /leaf

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/data_hamal?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      max-lifetime: 1800000
      idle-timeout: 60000
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  application:
    name: data-hamal-provider-leaf
  profiles:
    active: dev
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        group: data-hamal

data:
  hamal:
    leaf:
      type: segment # segment, snowflake
      name: DHNI # 当启动多个节点时, 节点名不可以重复哦～
      zookeeper:
        address: 127.0.0.1:21810

dubbo:
  application:
    name: ${spring.application.name}
    metadata-type: remote
    # 可选值 interface、instance、all，默认是 all，即接口级地址、应用级地址都注册
    register-mode: instance
  provider:
    token: true
  registry:
    address: nacos://${nacos.address:localhost}:8848?username=nacos&password=nacos
    group: data-hamal
  protocol:
    name: dubbo
    port: -1
