server:
  port: 9020
  servlet:
    context-path: /leaf

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/data_hamal?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      max-lifetime: 1800000
      idle-timeout: 60000
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  application:
    name: data-hamal-service-leaf
  profiles:
    active: dev

data:
  hamal:
    leaf:
      # 当启动多个节点时, 节点名不可以重复哦～
      name: leaf-node-1
      segment:
        enabled: false
      snowflake:
        enabled: true
        zk:
          address: 127.0.0.1
          port: 21810