dubbo:
  application:
    name: ${spring.application.name}
    metadata-type: remote
    # 可选值 interface、instance、all，默认是 all，即接口级地址、应用级地址都注册
    register-mode: instance
  provider:
    token: true
  registry:
    address: nacos://${spring.cloud.nacos.discovery.server-addr}?username=nacos&password=nacos
    group: ${spring.cloud.nacos.discovery.group}
    namespace: ${spring.cloud.nacos.discovery.namespace}
  protocol:
    name: dubbo
    port: -1
