spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          url-expression: uri
      routes:
        - id: data-hamal-service-hello
          uri: lb://data-hamal-service-hello
          predicates:
            - Path=/hello/**
        - id: data-hamal-service-filestorage
          uri: lb://data-hamal-service-filestorage
          predicates:
            - Path=/storage/file/**

data-hamal:
  auth:
    whites:
      - /login
      - /register